# Generated by Django 4.2.16 on 2024-11-30 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['nomi'], 'verbose_name': 'Ovqat', 'verbose_name_plural': 'Ovqatlar'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'ordering': ['nomi'], 'verbose_name': 'Ovqat turi', 'verbose_name_plural': 'Ovqat turlari'},
        ),
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.food', verbose_name='Ovqat'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.foodtype', verbose_name='Ovqat turi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='narxi',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='nomi',
            field=models.CharField(max_length=100, verbose_name='Ovqat nomi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='tarkibi',
            field=models.TextField(verbose_name='Ovqat tarkibi'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='nomi',
            field=models.CharField(max_length=100, verbose_name='Ovqat turi'),
        ),
    ]
